# Generated by Django 2.1.5 on 2020-04-10 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='ifsc',
            field=models.IntegerField(max_length=10),
        ),
    ]
