# Generated by Django 2.1.5 on 2020-04-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bankapi', '0002_auto_20200410_2125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='bank',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Bank',
        ),
    ]
